language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-28.0.3
  - android-28
  - Extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - addon-google_apis-google-28
BEFORE_INSTALL:
- ​​chmod + x gradlew
- export JAVA8_HOME = / usr / lib / jvm / java-8-oracle
- export JAVA_HOME = $ JAVA8_HOME
after_success:
- chmod + x ./upload-gh-pages. sh
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key: 3c842711753f810be0750cea482554a1f03ba708
  file_glob: true
  file: Users/moka/Documents/PaxKeyInjection/app/build/outputs/apk/release/*
  /
  on:
    repo: Vieony/PaxKeyInjection
    tags: true
script:
- ./gradlew build
